export enum UtilityEnum {
    CREATE_WHITEBOARD_MESSAGE_BOX_ACTION_ID = "create-whiteboard-message-box-action-id",
    MESSAGE_LABEL = "Send Message as per your wish",
    INPUT_LABEL = "Send your message",
    INPUT_PLACEHOLDER = "Write your message",
    MESSAGE_INPUT_BLOCK_ID = "message-input-block-id",
    MESSAGE_INPUT_ACTION_ID = "message-action-id",
    CANCEL = "Cancel",
    CLOSE_BLOCK_ID = "close-block-id",
    CLOSE_ACTION_ID = "close-action-id",
    SEND = "Send",
    SEND_BLOCK_ID = "send-block-id",
    SEND_ACTION_ID = "send-action-id",
    MESSAGE_MODAL_ID = "message-modal-id",
    MESSAGE_MODAL_TITLE = "Send Message",
    MESSAGE_BUTTON_ACTION_ID = "message-button-action-id",
    CREATE_BASIC_MESSAGE_BOX_ACTION_ID = "create-basic-message-box-id",
    PREVIEW_BLOCK_ID = "preview-block-id",
    OPEN_BUTTON_ACTION_ID = "open-button-action-id",
    DELETE_MESSAGE_ID = "delete-message",
}
